use_frameworks!

platform :ios, '9.0'

target 'MyLib_Example' do
  pod 'MyLib', :path => '../'

  target 'MyLib_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'MockingbirdFramework'
  end
end
